### ISSUE TITLE
Issues burning the img to sdcard.

### ISSUE THREAD

**Issue by AndrewCapon** [gabrielpgagne/pynq-zybo-z720#1]
Hi Gabriel,

Thanks for all this info, very good of you, but I have a slight issue:

The process runs through fine, but when I burnt the output/Zybo-Z7-20-3.0.1.img to a card, try to boot, nothing on the Zybo.

So I look at the SDCard and it is no good, linux just can't see anything useful at all. So I try to mount the img file, no luck either.

Diskpart just sees a single partition, unrecognisable.

So I'm guessing I am trying to create the SDCard incorrectly by just using "dd" to write the img file, I would expect a FAT partition with the output/boot and then an ext portion with the filesystem. This doesn't seem to be the case.

Could you please tell me where I am going wrong?

All the best

Andy

**Comment by gabrielpgagne** [comment]
Hello Andy,

I think I've had this problem happen once, when I forgot to unmount the SD card before `dd`'ing. I guess my OS tried to read it during `dd`, and it messed up the copy. Perhaps you can make sure you do that?

Hopefully your card isn't bricked, but make sure you follow these instructions (cited from [PYNQ docs](https://pynq.readthedocs.io/en/latest/appendix/sdcard.html)):

> Run umount /dev/sdd1, replacing sdd1 with whatever your SD card’s device name is (including the partition number).

**Comment by AndrewCapon** [comment]
Hi Gabriel,

Thanks, you are spot on.

I had tried writing to `sde` and it hadn't worked, so I used `sde1`. The reason `sde` hadn't worked is because the card was mounted. Doh.

Thanks for the help, and thanks very much for the work you have done getting this working.

I now have a `xilinx@pynq:~$` prompt :)

Cheers

Andy

**Comment by gabrielpgagne** [comment]
Happy to hear it worked. Well done !

Thank you for the kind words, I appreciate it :)

**Comment by AndrewCapon** [comment]
Hi Gabriel

Sorry to bother you but should this all boot up with files in the overlays folder?

I can see in the repo here for instance base.bit but can't find it anywhere on the sdcard!

If I try loading it:
```
from pynq.overlays.base import BaseOverlay

ol = BaseOverlay("base.bit")

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 from pynq.overlays.base import BaseOverlay
      3 ol = BaseOverlay("base.bit")

ModuleNotFoundError: No module named 'pynq.overlays.base'
```

Also I don't see the notebooks in this repo on the zybo either.

I'm thinking I must have done something wrong when building the sdcard, should this repo have been checked out recursively?

The board boots up with the FPGA unprogrammed as well, is that normal?

Thanks

Andy

**Comment by gabrielpgagne** [comment]
The notebooks should be installed in `~/jupyter_notebooks`.

For some reason I haven't had time to look into, this image build does not install `base.bit` by default. If I recall correctly, I had to manually SSH the files `__init__.py` and `base.{bit,hwh,py}` from this repo's `Zybo-Z7-20/base` to the Zybo's `~/pynq/overlays` folder.

<img width="618" alt="Screenshot 2024-04-06 at 09 01 32" src="https://github.com/gabrielpgagne/pynq-zybo-z720/assets/57460335/74a6b3e8-99ce-4695-9faa-92b17d763dae">

Finally, ensure you have a `/boot/boot.py` file. My boot script flashes the Zybo's LEDs:

```python
from time import sleep
from pynq.overlays.base import BaseOverlay

base = BaseOverlay("base.bit")

rgbleds = [base.rgbleds[i] for i in range(4, 6)]
leds = [base.leds[i] for i in range(4)]

# Toggle board LEDs leaving small LEDs lit
for i in range(8):
    [l.off() for l in leds]
    [rgbled.off() for rgbled in rgbleds]
    sleep(.2)
    [l.on() for l in leds]
    [rgbled.on(1) for rgbled in rgbleds]
    sleep(.2)

[rgbled.off() for rgbled in rgbleds]
```

**Comment by AndrewCapon** [comment]
Hi Gabriel,

Thanks very much for all this info, very good of you.

The /boot/boot.py is there and the same as you listed here with what looks like some previous code commented out at the top.

So I copied the three base files, rebooted and a little while after I get the prompt on the console the `Logic Configuration Done LED` lights green :)

No flashing LEDs though :(

if I then press the `Logic configuration reset Pushbutton`, and run the following:

```
from pynq.overlays.base import BaseOverlay

ol = BaseOverlay("base.bit")
```

Then the `Logic Configuration Done LED` lights green again, but:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [6], in <cell line: 3>()
      1 from pynq.overlays.base import BaseOverlay
----> 3 ol = BaseOverlay("base.bit")

File /usr/local/share/pynq-venv/lib/python3.10/site-packages/pynq/overlays/base.py:40, in BaseOverlay.__init__(self, bitfile, **kwargs)
     38 super().__init__(bitfile, **kwargs)
     39 if self.is_loaded():
---> 40     self.audio = self.audio_direct_0
     41     self.audio.configure()
     43     self.leds = self.leds_gpio.channel1

File /usr/local/share/pynq-venv/lib/python3.10/site-packages/pynq/overlay.py:363, in Overlay.__getattr__(self, key)
    358 """Overload of __getattr__ to return a driver for an IP or
    359 hierarchy. Throws an `RuntimeError` if the overlay is not loaded.
    360 
    361 """
    362 if self.is_loaded():
--> 363     return getattr(self._ip_map, key)
    364 else:
    365     raise RuntimeError("Overlay not currently loaded")

File /usr/local/share/pynq-venv/lib/python3.10/site-packages/pynq/overlay.py:931, in _IPMap.__getattr__(self, key)
    929     return mem
    930 else:
--> 931     raise AttributeError(
    932         "Could not find IP or hierarchy {} in overlay".format(key)
    933     )

AttributeError: Could not find IP or hierarchy audio_direct_0 in overlay
```

So something is a bit iffy there, I noticed `File /usr/local/share/pynq-venv/lib/python3.10/site-packages/pynq/overlays/base.py` and thought that might be the issue, but the contents are the same as the one I copied across to `~/pynq/overlays`.


Concerning the notebooks, in ~/jupyter_notebooks/getting_started I have:

```
xilinx@pynq:~/jupyter_notebooks/getting_started$ ls -ltr
total 900
drwxrwxrwx 2 xilinx xilinx   4096 Apr  5 10:51 images
-rw-rw-rw- 1 xilinx xilinx 863661 Apr  5 10:51 3_jupyter_notebooks_advanced_features.ipynb
-rw-rw-rw- 1 xilinx xilinx  17569 Apr  5 10:51 2_python_environment.ipynb
-rw-rw-rw- 1 xilinx xilinx  30068 Apr  5 10:51 1_jupyter_notebooks.ipynb
```

So the following are missing from this repo:

```
4_base_overlay_iop.ipynb  
5_base_overlay_video.ipynb  
6_base_overlay_audio.ipynb
```

Also all the interesting files in `base/nootbooks' doesn't seem to have made its way over to the zibo.

```
andrewcapon@ubuntu:~/PYNQ/boards/Zybo-Z7-20/base/notebooks$ ls -ltr
total 40
-rw-rw-r-- 1 andrewcapon andrewcapon 5690 Apr  5 11:13 GPIOs_test.ipynb
drwxrwxr-x 3 andrewcapon andrewcapon 4096 Apr  5 11:13 arduino
drwxrwxr-x 2 andrewcapon andrewcapon 4096 Apr  5 11:13 audio
drwxrwxr-x 2 andrewcapon andrewcapon 4096 Apr  5 11:13 microblaze
drwxrwxr-x 2 andrewcapon andrewcapon 4096 Apr  5 11:13 board
drwxrwxr-x 3 andrewcapon andrewcapon 4096 Apr  5 11:13 trace
drwxrwxr-x 3 andrewcapon andrewcapon 4096 Apr  5 11:13 rpi
drwxrwxr-x 3 andrewcapon andrewcapon 4096 Apr  5 11:13 pmod
drwxrwxr-x 3 andrewcapon andrewcapon 4096 Apr  5 11:13 video
```

I'm guessing maybe some other stuff from base must be missing?

Cheers

Andy

**Comment by gabrielpgagne** [comment]
For `base.py`, you're right, the commited version has an error in the GitHub. I'll push the fix, but essentially just **delete** the lines 40 and 41, since I've not included video/IOP/audio in the base bitstream of this repo:

```python
self.audio = self.audio_direct_0
self.audio.configure()
```

This is also why the notebooks 4, 5 and 6 are missing, since the IP is not in the base bitstream.

Finally, the base overlay (including notebooks) do not get installed from the build flow for some reason. So you should be able to just SSH the base notebooks into `~/jupyter_notebooks` :)

Best

GG

**Comment by AndrewCapon** [comment]
Hi Gabriel,

Thanks very much, I will give this a go tomorrow and let you know how it goes.

Cheers

Andy

**Comment by AndrewCapon** [comment]
Hi Gabriel,

Everything is good now, with your fixes.

Boots up and the RGB LEDS flash blue.

Tried a couple of the Base notebooks and all is working fine.

Once again thanks very much for all of this, you have saved me a lot of pain and scratching of the head to try and get this all going from scratch.

I'm going to try to get the Audio added to the bitstream today...

All the best

Andy

**Comment by gabrielpgagne** [comment]
Glad to hear you're up and running !

If you feel like it and get Audio working, feel free to open a PR to this repo!

Best

GG
